### ISSUE TITLE
Text disapears behind button

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#107]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=560#p70871

by RickDB » Tue Jan 19, 2016 3:31 pm

1) The green "SET" icon is misaligned in potrait mode as it overlaps the text label (name)
2) an empty white space below (like it expects more info in a new row)

![432392be-bf6a-11e5-9b93-e621e05ae5f6](https://cloud.githubusercontent.com/assets/3482284/12506594/778bed8a-c0f0-11e5-9b38-bb2586ebd80e.jpg)

**Comment by Jaap-Jan** [comment]
Per-zone temperature control is actually more of an enhancement. I think it's better to separate the two issues. I've got permanent override more or less working, I'll see if I can push it soon. Temporary override (where you can set a temperature and a date and time, after which the normal program is followed) is more of a problem, as we don't have a way to select both a date/time AND a temperature.

**Comment by RoadXY** [comment]
Extracted the feature request and made an new issue #112

**Comment by Jaap-Jan** [comment]
First problem (evohome device too large) is fixed. Second problem is I think, essentially the same as #110.

**Comment by galadril** [comment]
So the text issue is fixed? then we can close this issue :+1:

**Comment by Jaap-Jan** [comment]
The text issue (text appearing behind the button) still exists. Isn't that also a problem on other layouts?

**Comment by RoadXY** [comment]
@Jaap-jan what do you mean with "evohome device too large is fixed"?
You don't mend text then?

**Comment by Jaap-Jan** [comment]
No, I meant the problem that there was too much whitespace. The issue the user explained as "adds a an empty white space below (like it expects more info in a new row)"

![device-2016-01-21-005616](https://cloud.githubusercontent.com/assets/3482284/12446436/432392be-bf6a-11e5-9b93-e621e05ae5f6.jpg)
![device-2016-01-21-005616](https://cloud.githubusercontent.com/assets/804104/12467227/0fd5338e-bfda-11e5-8b4c-4d838d0216fe.png)

**Comment by galadril** [comment]
I think i've fixed the text overlay issues.. please validate

**Comment by Jaap-Jan** [comment]
Confirmed. But the height issue is back. If you apply this patch the issue is fixed and can be closed.
[fix-height.patch.zip](https://github.com/domoticz/domoticz-android/files/100524/fix-height.patch.zip)

**Comment by RoadXY** [comment]
Updated the issue in post one to clarify
