### ISSUE TITLE
Controlling of Events from Android APP no longer working

### ISSUE THREAD

**Issue by vojtishek** [domoticz/domoticz-android#711]
Hello everyone,

I have an issue after upgrading to payed version of Domoticz on Android with turning on/off specific events. UI just didn't reflecting my state and after refresh turned back to previous state. Web UI working as expecting. I'm using that quite often to turn off quickly event from mobile to do not get notification.

this is from protocol

2024-03-25 11:55:10.852 Status: [web:8080] Incoming connection from: 192.168.1.238
2024-03-25 11:55:15.482 Status: [WebServer] Deprecated RType (events) for API request. Call ignored, please use correct API Command! (192.168.1.238)

I'm running Domoticz server od RPI on Version: 2024.4

Any help more than appreciated

Thank you
Vojtech

**Smartphone (please complete the following information):**
 - Device: Samsung S23 Ultra
 - OS: Android 14
 - Domoticz app 0.2.370

**Comment by galadril** [comment]
I'm improving this currently.
https://play.google.com/apps/testing/nl.hnogames.domoticz

Plz apply for beta channel, this should be fixed there

**Comment by vojtishek** [comment]
Hello still receiveing error after the udpate from 14.4.

2024-04-18 10:51:18.567 Invalid API command received! (getevents)

**Comment by tootai** [comment]
Same here other way: v0.2.375 (9514) from 14/04/2024 doesnt connect anymore on 2023.x (arm v6) domoticz server as at least v0.2.370 (9442) does. Tested on Nexus5, S7 and RedmiNote9

**Comment by galadril** [comment]
> 2023.1

this was stated in the release notes.. i updated the app to only work with the new apis from the 2024 releases

**Comment by tootai** [comment]
I know it was stated but app update didn't mention anything about this.

You can't force users to update there whole installation ! At least propose to NOT update android app if users are not willing or propose a parameter in the app to be compatible with old API (or keep a version compatible). How many raspberry will go  garbage ? What about the cost of buying new material ? Nonsense

Where can we download the last compatible version for arm v6 servers ?

**Comment by tootai** [comment]
BTW, on some installation we use the payed version, money for nothing ?

**Comment by galadril** [comment]
If you don't update your Domoticz installation, then also don't update your mobile app.
There is a limit on how far you can go with backwards compatibility and willing to maintain.

I have two Domoticz setups on which keep track of 2 different versions, to validate the apps against.. I'm not going to install 100 Domoticz setups with all versions, to test against them for backwards compatibility.

Check this issue thread on how many breaking changes were introduced on Domoticz;
https://github.com/domoticz/domoticz-android/issues/692

It was in the release notes of the app:
![image](https://github.com/domoticz/domoticz-android/assets/14561640/eb21f2c3-7505-486b-87be-b90aba070ab8)


Please don't continue off-topic on this thread, because ill remove the comments

**Comment by galadril** [comment]
@vojtishek sorry didnt understand the real issue :D.. thought it was about loading the events list.. but i now notice its indeed on enable/disabling the events... I have a fix

**Comment by tootai** [comment]
Don't know if you get the point: armv6 Domoticz servers are sticked with 2023.x version, 2024.x version are only compatible with arm v7. This mean, all Domoticz Pi arm v6 running as server have to go to garbage if android/apple app is only compatible with 2024.x+

Please tell me where we could download latest apk compatible with old API, we don't ask more.

**Comment by vojtishek** [comment]
Hey, yes It was regarding enable/disabling the events from android app.
I have this version of server

Version: 2024.4
Build Hash: 731719420
Compile Date: 2024-01-30 09:16:34
dzVents Version: 3.1.8
Python Version: None

Version of Android app 0.2.375 (9514)

I'm already beta tester.

Still getting same error 

2024-04-21 16:44:37.164 Invalid API command received! (getevents)

**Comment by vojtishek** [comment]
Hi, any update, still stucked with this issue and quite annoying as I've used this feature quite often?

**Comment by galadril** [comment]
Have you tried Domoticz version 
693 (0.2.376 (9591))
?

**Comment by vojtishek** [comment]
Now it works, thanks

**Comment by pizzulicchio** [comment]
Yes, it works now. The "events" are listed and it's possible to enable/disable them.
thanks
